### ISSUE TITLE
I want to create new Shopify Product by Scalable Press API

### ISSUE THREAD

**Issue by tommydo1905** [gcauchis/ScalablePress4J#2]
Hi,
I code private tool to create Shopify Products with Scalable Press API. But i don't know. Can you help me? I am using PHP to code my tools.
Thank you so much

**Comment by gcauchis** [comment]
Hi,
The [API is realy well documented: https://scalablepress.com/docs](https://scalablepress.com/docs/). The only difficulty is the [authentication](https://scalablepress.com/docs/#authentication), you had to edit your request header. The request are just http GET/POST with json content and the api is always up for testing.
My knowledge in PHP is too old so i don't think i can help you more, but fell free if you have question.
Regards,

**Comment by tommydo1905** [comment]
I can't create Product with API, i can create Design and i don't know about next step :)

**Comment by gcauchis** [comment]
You cannot create a product.

The process:
 * Make a quote with your design applied to an API product. [(see Quote API)](https://scalablepress.com/docs/#quote-api)
 * Then you can make an order with the "orderToken". [(see Order API)](https://scalablepress.com/docs/#order-api)
 * Finally it's billing time. [(see Biling API)](https://scalablepress.com/docs/#billing-apii)

**Comment by tommydo1905** [comment]
I want to link with my Shopify Store. Can you show me this process?

**Comment by gcauchis** [comment]
Sorry, i have zero knowledge in Shopify application, so i can't help you for an integration.
The process is the one i already give you, and as i say the [API is realy well documented: https://scalablepress.com/docs](https://scalablepress.com/docs).

**Comment by gcauchis** [comment]
Hi @tommydo1905,

It seems that scalable press has already made an integration do Shopify: [https://scalablepress.com/shopify](https://scalablepress.com/shopify).

**Comment by tommydo1905** [comment]
I used Scalable Press for my Shopify Store. But i can't create Products by tool with API, i must create new products and link with Scalable Press by hand :)
